added all models and tests for those models
NickChirgin/taskmanager pull request #5
Opened 2023-01-30 11:52 UTC by NickChirgin

2023-01-30 16:16 UTC, greybutton requested changes

2023-01-30 16:16 UTC, greybutton commented on Gemfile
> +  gem 'bcrypt'
этот гем нужен для работы везде, не только для разработки

2023-01-30 16:16 UTC, greybutton commented on test/test_helper.rb
> +require 'factory_bot_rails'
почему добавил?

2023-01-30 16:20 UTC, NickChirgin commented on test/test_helper.rb
> +require 'factory_bot_rails'
![image](https://user-images.githubusercontent.com/56773138/215533223-e029dbe8-b009-4510-9642-744c108cd8b6.png)
без require выдает ошибку

2023-02-06 07:03 UTC, greybutton approved these changes

2023-02-06 08:06 UTC, merged